/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './../routes/__root'
import { Route as SlowImport } from './../routes/slow'
import { Route as FastImport } from './../routes/fast'
import { Route as IndexImport } from './../routes/index'

// Create/Update Routes

const SlowRoute = SlowImport.update({
  path: '/slow',
  getParentRoute: () => rootRoute,
} as any)

const FastRoute = FastImport.update({
  path: '/fast',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/fast': {
      preLoaderRoute: typeof FastImport
      parentRoute: typeof rootRoute
    }
    '/slow': {
      preLoaderRoute: typeof SlowImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  FastRoute,
  SlowRoute,
])

/* prettier-ignore-end */
